<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'App__Entity__User__CLASSMETADATA__' => 0,
'App__Entity__Infraction__CLASSMETADATA__' => 1,
'App__Entity__Engine__CLASSMETADATA__' => 2,
'App__Entity__Driver__CLASSMETADATA__' => 3,
'App__Entity__Team__CLASSMETADATA__' => 4,

], [

0 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\User',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\UserRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'email' => $o[2],
                    'roles' => $o[3],
                    'password' => $o[4],
                    'isActive' => $o[5],
                    'createdAt' => $o[6],
                    'updatedAt' => $o[7],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'is_active' => 'isActive',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'email' => 'email',
                    'roles' => 'roles',
                    'password' => 'password',
                    'isActive' => 'is_active',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'user',
                    'quoted' => true,
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\User',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'json',
                'string',
                'boolean',
                'datetime',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'isActive',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'email',
                'roles',
                'password',
                'is_active',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 180,
            ],
            'unique' => [
                2 => true,
            ],
        ],
    ],
    $o[0],
    []
); } },
1 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Infraction',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\InfractionRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'occurredAt' => $o[2],
                    'raceName' => $o[3],
                    'description' => $o[4],
                    'type' => $o[5],
                    'amount' => $o[6],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'occurred_at' => 'occurredAt',
                    'race_name' => 'raceName',
                    'description' => 'description',
                    'type' => 'type',
                    'amount' => 'amount',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'occurredAt' => 'occurred_at',
                    'raceName' => 'race_name',
                    'description' => 'description',
                    'type' => 'type',
                    'amount' => 'amount',
                ],
            ],
            'table' => [
                [
                    'name' => 'infraction',
                ],
            ],
            'associationMappings' => [
                [
                    'driver' => $o[7],
                    'team' => $o[9],
                ],
            ],
            'idGenerator' => [
                $o[11],
            ],
            'name' => [
                'App\\Entity\\Infraction',
                8 => 'driver_id',
                10 => 'team_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'datetime',
                'string',
                'text',
                'string',
                'decimal',
            ],
            'fieldName' => [
                1 => 'id',
                'occurredAt',
                'raceName',
                'description',
                'type',
                'amount',
            ],
            'columnName' => [
                1 => 'id',
                'occurred_at',
                'race_name',
                'description',
                'type',
                'amount',
            ],
            'length' => [
                3 => 160,
                5 => 20,
            ],
            'precision' => [
                6 => 12,
            ],
            'scale' => [
                6 => 2,
            ],
            'fetch' => [
                7 => 2,
                9 => 2,
            ],
            'sourceEntity' => [
                7 => 'App\\Entity\\Infraction',
                9 => 'App\\Entity\\Infraction',
            ],
            'inversedBy' => [
                7 => 'infractions',
                9 => 'infractions',
            ],
            'sourceToTargetKeyColumns' => [
                7 => [
                    'driver_id' => 'id',
                ],
                9 => [
                    'team_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                7 => [
                    'id' => 'driver_id',
                ],
                9 => [
                    'id' => 'team_id',
                ],
            ],
            'joinColumns' => [
                7 => [
                    $o[8],
                ],
                9 => [
                    $o[10],
                ],
            ],
            'joinColumnFieldNames' => [
                7 => [
                    'driver_id' => 'driver_id',
                ],
                9 => [
                    'team_id' => 'team_id',
                ],
            ],
            'deferrable' => [
                8 => false,
                10 => false,
            ],
            'unique' => [
                8 => false,
                10 => false,
            ],
            'onDelete' => [
                8 => 'SET NULL',
                10 => 'SET NULL',
            ],
            'nullable' => [
                8 => true,
                10 => true,
            ],
            'referencedColumnName' => [
                8 => 'id',
                10 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                7 => 'driver',
                9 => 'team',
            ],
            'targetEntity' => [
                7 => 'App\\Entity\\Driver',
                9 => 'App\\Entity\\Team',
            ],
        ],
    ],
    $o[0],
    []
); } },
2 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneOwningSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Engine',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\EngineRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'brand' => $o[2],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'brand' => 'brand',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'brand' => 'brand',
                ],
            ],
            'table' => [
                [
                    'name' => 'engine',
                ],
            ],
            'associationMappings' => [
                [
                    'team' => $o[3],
                ],
            ],
            'idGenerator' => [
                $o[5],
            ],
            'name' => [
                'App\\Entity\\Engine',
                4 => 'team_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
            ],
            'fieldName' => [
                1 => 'id',
                'brand',
            ],
            'columnName' => [
                1 => 'id',
                'brand',
            ],
            'length' => [
                2 => 120,
            ],
            'cascade' => [
                3 => [
                    'persist',
                ],
            ],
            'fetch' => [
                3 => 2,
            ],
            'sourceEntity' => [
                3 => 'App\\Entity\\Engine',
            ],
            'inversedBy' => [
                3 => 'engine',
            ],
            'sourceToTargetKeyColumns' => [
                3 => [
                    'team_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                3 => [
                    'id' => 'team_id',
                ],
            ],
            'joinColumns' => [
                3 => [
                    $o[4],
                ],
            ],
            'joinColumnFieldNames' => [
                3 => [
                    'team_id' => 'team_id',
                ],
            ],
            'deferrable' => [
                4 => false,
            ],
            'unique' => [
                4 => true,
            ],
            'onDelete' => [
                4 => 'CASCADE',
            ],
            'nullable' => [
                4 => false,
            ],
            'referencedColumnName' => [
                4 => 'id',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                3 => 'team',
            ],
            'targetEntity' => [
                3 => 'App\\Entity\\Team',
            ],
        ],
    ],
    $o[0],
    []
); } },
3 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ManyToOneAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\JoinColumnMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\JoinColumnMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Driver',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\DriverRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'firstName' => $o[2],
                    'lastName' => $o[3],
                    'isStarter' => $o[4],
                    'licensePoints' => $o[5],
                    'status' => $o[6],
                    'f1StartDate' => $o[7],
                    'createdAt' => $o[8],
                    'updatedAt' => $o[9],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'first_name' => 'firstName',
                    'last_name' => 'lastName',
                    'is_starter' => 'isStarter',
                    'license_points' => 'licensePoints',
                    'status' => 'status',
                    'f1_start_date' => 'f1StartDate',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'firstName' => 'first_name',
                    'lastName' => 'last_name',
                    'isStarter' => 'is_starter',
                    'licensePoints' => 'license_points',
                    'status' => 'status',
                    'f1StartDate' => 'f1_start_date',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'driver',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'team' => $o[10],
                    'infractions' => $o[12],
                ],
            ],
            'idGenerator' => [
                $o[13],
            ],
            'name' => [
                'App\\Entity\\Driver',
                11 => 'team_id',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'string',
                'boolean',
                'integer',
                'string',
                'date',
                'datetime',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'firstName',
                'lastName',
                'isStarter',
                'licensePoints',
                'status',
                'f1StartDate',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'first_name',
                'last_name',
                'is_starter',
                'license_points',
                'status',
                'f1_start_date',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 100,
                100,
                6 => 20,
            ],
            'fetch' => [
                10 => 2,
                12 => 2,
            ],
            'sourceEntity' => [
                10 => 'App\\Entity\\Driver',
                12 => 'App\\Entity\\Driver',
            ],
            'inversedBy' => [
                10 => 'drivers',
            ],
            'sourceToTargetKeyColumns' => [
                10 => [
                    'team_id' => 'id',
                ],
            ],
            'targetToSourceKeyColumns' => [
                10 => [
                    'id' => 'team_id',
                ],
            ],
            'joinColumns' => [
                10 => [
                    $o[11],
                ],
            ],
            'joinColumnFieldNames' => [
                10 => [
                    'team_id' => 'team_id',
                ],
            ],
            'deferrable' => [
                11 => false,
            ],
            'unique' => [
                11 => false,
            ],
            'onDelete' => [
                11 => 'SET NULL',
            ],
            'nullable' => [
                11 => true,
            ],
            'referencedColumnName' => [
                11 => 'id',
            ],
            'mappedBy' => [
                12 => 'driver',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                10 => 'team',
                12 => 'infractions',
            ],
            'targetEntity' => [
                10 => 'App\\Entity\\Team',
                12 => 'App\\Entity\\Infraction',
            ],
        ],
    ],
    $o[0],
    []
); } },
4 => new class() implements \Symfony\Component\Cache\Traits\CachedValueInterface { public function getValue(): mixed { return \Symfony\Component\VarExporter\Internal\Hydrator::hydrate(
    $o = [
        clone (($p = &\Symfony\Component\VarExporter\Internal\Registry::$prototypes)['Doctrine\\ORM\\Mapping\\ClassMetadata'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\ClassMetadata')),
        clone ($p['Doctrine\\ORM\\Mapping\\FieldMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\FieldMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone $p['Doctrine\\ORM\\Mapping\\FieldMapping'],
        clone ($p['Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToOneInverseSideMapping')),
        clone ($p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping')),
        clone $p['Doctrine\\ORM\\Mapping\\OneToManyAssociationMapping'],
        clone ($p['Doctrine\\ORM\\Id\\IdentityGenerator'] ?? \Symfony\Component\VarExporter\Internal\Registry::p('Doctrine\\ORM\\Id\\IdentityGenerator')),
    ],
    null,
    [
        'stdClass' => [
            'namespace' => [
                'App\\Entity',
            ],
            'rootEntityName' => [
                'App\\Entity\\Team',
            ],
            'customRepositoryClassName' => [
                'App\\Repository\\TeamRepository',
            ],
            'identifier' => [
                [
                    'id',
                ],
            ],
            'generatorType' => [
                4,
            ],
            'fieldMappings' => [
                [
                    'id' => $o[1],
                    'name' => $o[2],
                    'createdAt' => $o[3],
                    'updatedAt' => $o[4],
                ],
            ],
            'fieldNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'created_at' => 'createdAt',
                    'updated_at' => 'updatedAt',
                ],
            ],
            'columnNames' => [
                [
                    'id' => 'id',
                    'name' => 'name',
                    'createdAt' => 'created_at',
                    'updatedAt' => 'updated_at',
                ],
            ],
            'table' => [
                [
                    'name' => 'team',
                ],
            ],
            'lifecycleCallbacks' => [
                [
                    'prePersist' => [
                        'onPrePersist',
                    ],
                    'preUpdate' => [
                        'onPreUpdate',
                    ],
                ],
            ],
            'associationMappings' => [
                [
                    'engine' => $o[5],
                    'drivers' => $o[6],
                    'infractions' => $o[7],
                ],
            ],
            'idGenerator' => [
                $o[8],
            ],
            'name' => [
                'App\\Entity\\Team',
            ],
            'id' => [
                1 => true,
            ],
            'type' => [
                1 => 'integer',
                'string',
                'datetime',
                'datetime',
            ],
            'fieldName' => [
                1 => 'id',
                'name',
                'createdAt',
                'updatedAt',
            ],
            'columnName' => [
                1 => 'id',
                'name',
                'created_at',
                'updated_at',
            ],
            'length' => [
                2 => 120,
            ],
            'unique' => [
                2 => true,
            ],
            'cascade' => [
                5 => [
                    'persist',
                    'remove',
                ],
                [
                    'persist',
                ],
            ],
            'fetch' => [
                5 => 2,
                2,
                2,
            ],
            'sourceEntity' => [
                5 => 'App\\Entity\\Team',
                'App\\Entity\\Team',
                'App\\Entity\\Team',
            ],
            'mappedBy' => [
                5 => 'team',
                'team',
                'team',
            ],
        ],
        'Doctrine\\ORM\\Mapping\\AssociationMapping' => [
            'fieldName' => [
                5 => 'engine',
                'drivers',
                'infractions',
            ],
            'targetEntity' => [
                5 => 'App\\Entity\\Engine',
                'App\\Entity\\Driver',
                'App\\Entity\\Infraction',
            ],
        ],
    ],
    $o[0],
    []
); } },

]];
