<?php

namespace ContainerQfs5JZE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEngineRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\EngineRepository' shared autowired service.
     *
     * @return \App\Repository\EngineRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\EngineRepository'] = new \App\Repository\EngineRepository(($container->services['doctrine'] ?? $container->load('getDoctrineService')));
    }
}
