<?php

namespace ContainerQfs5JZE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfractionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\InfractionController' shared autowired service.
     *
     * @return \App\Controller\InfractionController
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService'));

        $container->services['App\\Controller\\InfractionController'] = $instance = new \App\Controller\InfractionController($a, new \App\Service\InfractionManager($a, ($container->privates['logger'] ?? self::getLoggerService($container))), ($container->privates['validator'] ?? $container->load('getValidatorService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InfractionController', $container));

        return $instance;
    }
}
