<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQfs5JZE\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQfs5JZE/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerQfs5JZE.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerQfs5JZE\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerQfs5JZE\App_KernelProdContainer([
    'container.build_hash' => 'Qfs5JZE',
    'container.build_id' => '05574773',
    'container.build_time' => 1762523543,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQfs5JZE');
