<?php

namespace ContainerAJI9jl1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O1QQocEService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private '.service_locator.O1QQocE' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.O1QQocE'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\InfractionRepository', 'getInfractionRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\InfractionRepository',
        ]);
    }
}
