<?php

namespace ContainerAJI9jl1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfractionManagerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'App\Service\InfractionManager' shared autowired service.
     *
     * @return \App\Service\InfractionManager
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/InfractionManager.php';

        return $container->privates['App\\Service\\InfractionManager'] = new \App\Service\InfractionManager(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['logger'] ?? self::getLoggerService($container)));
    }
}
