<?php

namespace ContainerAJI9jl1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getInfractionControllerService extends App_KernelTestDebugContainer
{
    /**
     * Gets the public 'App\Controller\InfractionController' shared autowired service.
     *
     * @return \App\Controller\InfractionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/InfractionController.php';

        $container->services['App\\Controller\\InfractionController'] = $instance = new \App\Controller\InfractionController(($container->services['doctrine.orm.default_entity_manager'] ?? $container->load('getDoctrine_Orm_DefaultEntityManagerService')), ($container->privates['App\\Service\\InfractionManager'] ?? $container->load('getInfractionManagerService')), ($container->privates['validator'] ?? $container->load('getValidatorService')));

        $instance->setContainer(($container->privates['.service_locator.O2p6Lk7'] ?? $container->load('get_ServiceLocator_O2p6Lk7Service'))->withContext('App\\Controller\\InfractionController', $container));

        return $instance;
    }
}
