<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAJI9jl1\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAJI9jl1/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerAJI9jl1.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerAJI9jl1\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerAJI9jl1\App_KernelTestDebugContainer([
    'container.build_hash' => 'AJI9jl1',
    'container.build_id' => '0885698b',
    'container.build_time' => 1762525904,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAJI9jl1');
