<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container697oYWi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container697oYWi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container697oYWi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container697oYWi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container697oYWi\App_KernelDevDebugContainer([
    'container.build_hash' => '697oYWi',
    'container.build_id' => '83dac402',
    'container.build_time' => 1762524750,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container697oYWi');
