<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'api_login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/api/login']], [], [], []],
    'api_user_create' => [[], ['_controller' => 'App\\Controller\\AuthController::create'], [], [['text', '/api/user/create']], [], [], []],
    'api_driver_list' => [[], ['_controller' => 'App\\Controller\\DriverController::list'], [], [['text', '/api/driver']], [], [], []],
    'api_driver_get' => [['id'], ['_controller' => 'App\\Controller\\DriverController::get'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/driver']], [], [], []],
    'api_infractions_create' => [[], ['_controller' => 'App\\Controller\\InfractionController::create'], [], [['text', '/api/infractions']], [], [], []],
    'api_infractions_list' => [[], ['_controller' => 'App\\Controller\\InfractionController::list'], [], [['text', '/api/infractions']], [], [], []],
    'api_team_drivers_list' => [['id'], ['_controller' => 'App\\Controller\\TeamController::listDrivers'], [], [['text', '/drivers'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/team']], [], [], []],
    'api_team_drivers_update' => [['id'], ['_controller' => 'App\\Controller\\TeamController::updateDrivers'], [], [['text', '/drivers'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/team']], [], [], []],
    'api_team_list' => [[], ['_controller' => 'App\\Controller\\TeamController::list'], [], [['text', '/api/team']], [], [], []],
    'App\Controller\AuthController::login' => [[], ['_controller' => 'App\\Controller\\AuthController::login'], [], [['text', '/api/login']], [], [], []],
    'App\Controller\AuthController::create' => [[], ['_controller' => 'App\\Controller\\AuthController::create'], [], [['text', '/api/user/create']], [], [], []],
    'App\Controller\DriverController::list' => [[], ['_controller' => 'App\\Controller\\DriverController::list'], [], [['text', '/api/driver']], [], [], []],
    'App\Controller\DriverController::get' => [['id'], ['_controller' => 'App\\Controller\\DriverController::get'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/api/driver']], [], [], []],
    'App\Controller\InfractionController::create' => [[], ['_controller' => 'App\\Controller\\InfractionController::create'], [], [['text', '/api/infractions']], [], [], []],
    'App\Controller\InfractionController::list' => [[], ['_controller' => 'App\\Controller\\InfractionController::list'], [], [['text', '/api/infractions']], [], [], []],
    'App\Controller\TeamController::listDrivers' => [['id'], ['_controller' => 'App\\Controller\\TeamController::listDrivers'], [], [['text', '/drivers'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/team']], [], [], []],
    'App\Controller\TeamController::updateDrivers' => [['id'], ['_controller' => 'App\\Controller\\TeamController::updateDrivers'], [], [['text', '/drivers'], ['variable', '/', '[^/]++', 'id', true], ['text', '/api/team']], [], [], []],
    'App\Controller\TeamController::list' => [[], ['_controller' => 'App\\Controller\\TeamController::list'], [], [['text', '/api/team']], [], [], []],
];
