<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Infraction extends \App\Entity\Infraction implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'amount' => [parent::class, 'amount', null, 16],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null, 16],
        "\0".parent::class."\0".'driver' => [parent::class, 'driver', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'occurredAt' => [parent::class, 'occurredAt', null, 16],
        "\0".parent::class."\0".'raceName' => [parent::class, 'raceName', null, 16],
        "\0".parent::class."\0".'team' => [parent::class, 'team', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        'amount' => [parent::class, 'amount', null, 16],
        'description' => [parent::class, 'description', null, 16],
        'driver' => [parent::class, 'driver', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'occurredAt' => [parent::class, 'occurredAt', null, 16],
        'raceName' => [parent::class, 'raceName', null, 16],
        'team' => [parent::class, 'team', null, 16],
        'type' => [parent::class, 'type', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
